stages:
  - build
  - deploy

variables:
  # This variable will be populated by the 'deploy-terraform' job artifact
  VUE_APP_API_URL: "$API_GATEWAY_URL"

build-fastapi:
  stage: build
  script:
    - cd backend && python bootstrap.py
  artifacts:
    paths:
      - backend/fastapi.zip

build-frontend:
  stage: build
  # It's a best practice to use a Docker image with the specific Node version you need
  image: node:20.17.0
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist

deploy-terraform:
  stage: deploy
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
    # Generate an artifact with the outputs from Terraform.
    # This artifact can be used by any subsequent job in the pipeline.
    - |
      cat > ../output.env <<EOF
      API_GATEWAY_URL=$(terraform output -raw api_url)
      FRONTEND_URL=$(terraform output -raw frontend_url)
      CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)
      S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name)
      EOF
  artifacts:
    reports:
      dotenv: ../output.env

deploy-frontend:
  stage: deploy
  # This job needs the artifacts from both build-frontend (to get the 'dist' folder)
  # and deploy-terraform (to get the environment variables like CLOUDFRONT_ID).
  dependencies:
    - build-frontend
    - deploy-terraform
  script:
    # No need to cd, build, or install. We work from the project root.
    # The 'dist' folder is available at 'frontend/dist' thanks to the artifact download.
    # The $S3_BUCKET_NAME and $CLOUDFRONT_ID variables are available from the terraform artifact.
    - aws s3 sync frontend/dist/ s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"