stages:
  - build
  - deploy

variables:
  VUE_APP_API_URL: "$API_GATEWAY_URL"  # This will be replaced with the actual URL

build-fastapi:
  stage: build
  script:
    - cd backend && python bootstrap.py
  artifacts:
    paths:
      - backend/fastapi.zip

build-frontend:
  stage: build
  script:
    - cd frontend
    - ~/.nvm/versions/node/v20.17.0/bin/npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist

deploy-terraform:
  stage: deploy
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
    - |
      cat > ../api_url.env <<EOF
      API_GATEWAY_URL=$(terraform output -raw api_url)
      FRONTEND_URL=$(terraform output -raw frontend_url)
      LAMBDA_ARN=$(terraform output -raw lambda_function_arn)
      EOF
    - cat ../api_url.env  # Verify file contents
  artifacts:
    reports:
      dotenv: ../api_url.env
    paths:
      - terraform/.terraform.lock.hcl